// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdwcLYgTWRMXRl8aDUNF-OFi9yATnS3x0',
    appId: '1:826190275007:web:19e511433ed7ff04cb810a',
    messagingSenderId: '826190275007',
    projectId: 'chat-app-e85bd',
    authDomain: 'chat-app-e85bd.firebaseapp.com',
    storageBucket: 'chat-app-e85bd.appspot.com',
    measurementId: 'G-8Z2N984WS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnT4KRv838E6Zhpu7y1L90P2PJn4qEHhw',
    appId: '1:826190275007:android:274fa8a38c9af672cb810a',
    messagingSenderId: '826190275007',
    projectId: 'chat-app-e85bd',
    storageBucket: 'chat-app-e85bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj2oBIn9syTNEbzPtz3LdpeZ1FtAs8kHQ',
    appId: '1:826190275007:ios:565166639185234ecb810a',
    messagingSenderId: '826190275007',
    projectId: 'chat-app-e85bd',
    storageBucket: 'chat-app-e85bd.appspot.com',
    iosClientId: '826190275007-jso7d4rp1hrjhkl9ep1slufb78pbetfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj2oBIn9syTNEbzPtz3LdpeZ1FtAs8kHQ',
    appId: '1:826190275007:ios:565166639185234ecb810a',
    messagingSenderId: '826190275007',
    projectId: 'chat-app-e85bd',
    storageBucket: 'chat-app-e85bd.appspot.com',
    iosClientId: '826190275007-jso7d4rp1hrjhkl9ep1slufb78pbetfi.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
